### ISSUE TITLE
Feature request: Show individual round scores

### ISSUE THREAD

**Issue by DeltaLeeds** [badoge/guessr.tv#1]
* Show individual round scores and how much they are off by or their specific guess.
* Add "pts" or "points" after the scores in the scoreboard as I get chatters confused on the scores on the scoreboard being their viewer count guess. 

So something like this:
![image](https://github.com/badoge/guessr.tv/assets/19412163/5949e867-e5d9-455f-beef-a7ec164d1df0)

**Comment by badoge** [comment]
That looks like too much text to include on the leaderboard
I'll see what I can do and include it in the next update in a couple days :)

**Comment by DeltaLeeds** [comment]
Maybe something like adding another tab for rounds so that it doesn't clutter too much? Something like this:
![image](https://github.com/badoge/guessr.tv/assets/19412163/e33bb46d-a4a4-4083-9394-db8f76706e7c)

**Comment by badoge** [comment]
This seems like a better solution, I'll add it after I'm done with a couple other things :)

**Comment by DeltaLeeds** [comment]
Of course, take your time, thank you for making the game. My chat and I loved it! Can't wait to see what updates you have in store for us!

**Comment by badoge** [comment]
I forgot about this and remembered it just yesterday ![1](https://github.com/badoge/guessr.tv/assets/18620902/ad901ea1-b603-4b48-9c0b-abc417edcaa0) should be live now :)

It only shows up for normal mode in the viewers or followers game

**Comment by DeltaLeeds** [comment]
Can't wait to try it out! Thanks for letting me know!

**Comment by DeltaLeeds** [comment]
Oh I have one more suggestion, can there be another tab showing people's guesses? Or if not another tab, at least in the round results have something like 
```
4,818 (34 off)
4,802 (37 off)
```
so that streamers can know how off people's guesses are?

**Comment by badoge** [comment]
I don't know about that ![1](https://github.com/badoge/guessr.tv/assets/18620902/c332141e-2285-4fe9-816c-290beff313a2) you can just look at chat to see what people guessed and you can look at the score to see how far off they were

**Comment by DeltaLeeds** [comment]
> I don't know about that ![1](https://user-images.githubusercontent.com/18620902/269688229-c332141e-2285-4fe9-816c-290beff313a2.png) you can just look at chat to see what people guessed and you can look at the score to see how far off they were

It's hard to do when the chat is crowded and is extra work for the streamer but if it's too much work from your part then I understand. I think this is good enough for now anyway, but it would better if it showed that feature, might just be me though. Alright I'll close the issue, thanks for the site and thanks for implementing round results!!
