### ISSUE TITLE
Bug: Two scores in one round

### ISSUE THREAD

**Issue by DeltaLeeds** [badoge/guessr.tv#2]
* When the streamer guesses in chat and in the site it counts twice.
![image](https://github.com/badoge/guessr.tv/assets/19412163/1777f49f-25a8-4c32-a87a-e2b25143611c)

**Comment by badoge** [comment]
fixed in f1dd65a3fda2113439ad71cf56e63fe5beff410c

**Comment by DeltaLeeds** [comment]
Is that fix live yet? Because a streamer playing the game still had this issue. They can get up to 10000 points each round guessing twice.

**Comment by badoge** [comment]
They would need to reload the site to get the updated version, might even need to hard reload (ctrl + f5)

**Comment by DeltaLeeds** [comment]
> They would need to reload the site to get the updated version, might even need to hard reload (ctrl + f5)

Oh yeah, I just tested in my own stream and it seems to work fine. It's weird that it didn't work for her stream because she literally just started streaming this game about an hour ago haha. Thank you for letting me know it's fixed!
